# Delay value
delay: 2 # in ticks
# Default delay in Minecraft is 20 ticks

# Mode options:
# pvp - No hit delay only applies in player versus player combat.
# evp - No hit delay only applies when entities attack players.
# pvp-evp - No hit delay applies to both PvP and EvP interactions as long as a player is involved.
# any - No hit delay applies to any entity interactions.
# player-only - No hit delay applies when players attack any entity, but entities do not have no hit delay when attacking.
mode: any

# Option to apply hit delay only to damage caused by MythicMobs skills and not to normal attacks.
only-Mythicmob-damage-hit-delay: false

# In-game you can use the following commands:
# /setdelay <value> - Change the delay value in ticks.
# /getdelay - Get the current hit delay in ticks.
# /setmode <mode> - Change the mode ('pvp', 'evp', 'pvp-evp', 'any', 'player-only').
# /getmode - Get the current mode.
# /reloadconfig - Reload the plugin configuration.
