name: NoHitDelay
version: '1.1'
main: newamazingpvp.nohitdelay.NoHitDelay
commands:
  nohitdelay:
    description: Manage hit delay settings.
    usage: /nohitdelay <setdelay|getdelay|setmode|getmode|reloadconfig> [value]
    permission: nohitdelay.manage
    default: op

