name: NoHitDelay
version: '${project.version}'
main: newamazingpvp.nohitdelay.NoHitDelay
folia-supported: true
description: Customize entity hit invulnerability delay (no-damage ticks)
commands:
  nohitdelay:
    description: Manage hit delay settings.
    usage: /nohitdelay <setdelay|getdelay|setmode|getmode|reloadconfig> [value]
    permission: nohitdelay.manage
permissions:
  nohitdelay.manage:
    description: Allows managing NoHitDelay settings.
    default: op
