name: NoHitDelay
version: '1.0'
main: newamazingpvp.nohitdelay.NoHitDelay
commands:
  setdelay:
    description: Set the hit delay value.
    usage: /setdelay <delay>
    permission: nohitdelay.setdelay
  getdelay:
    description: Get the hit delay value.
    usage: /getdelay
    permission: nohitdelay.getdelay
  setmode:
    description: Set the hit delay mode.
    usage: /setmode <mode>
    permission: nohitdelay.setmode
  getmode:
    description: Get the hit delay mode.
    usage: /getmode
    permission: nohitdelay.getmode
