# Delay value
delay: 2 # in ticks
# Default delay in Minecraft is 20 ticks

# Mode options:
# pvp - No hit delay only applies in player versus player combat.
# evp - No hit delay only applies when entities attack players.
# pvp-evp - No hit delay applies to both PvP and EvP interactions as long as a player is involved.
# any - No hit delay applies to any entity interactions.
# player-only - No hit delay applies when players attack any entity, but entities do not have no hit delay when attacking.
mode: any

# Option to apply hit delay only to damage caused by MythicMobs skills and not to normal attacks.
only-Mythicmob-damage-hit-delay: false

messages:
  prefix: "&f[NoHitDelay] "
  use-prefix: true
  delay-set: "&aDelay set to: &e%value%&a. Do make sure the delay is at least 2 because setting it below that will make some hits not register."
  invalid-delay: "&cInvalid delay value. Please enter a number."
  usage-setdelay: "&cUsage: /nohitdelay setdelay <delay>"
  current-delay: "&aDelay is currently set to: &e%value%"
  mode-set: "&aMode set to: &e%value%&a."
  invalid-mode: "&cInvalid mode value. Please use 'pvp', 'evp', 'pvp-evp', 'any', or 'player-only'."
  usage-setmode: "&cUsage: /nohitdelay setmode <mode>"
  current-mode: "&aMode is currently set to: &e%value%"
  config-reloaded: "&aConfiguration reloaded."
  command-list:
    - "&fnohitdelay command list"
    - "&f"
    - "&f/nohitdelay setdelay <amount> &7(~~~)"
    - "&f/nohitdelay getdelay &7(~~~)"
    - "&f/nohitdelay setmode <mode> &7(~~~)"
    - "&f/nohitdelay getmode &7(~~~)"
    - "&f/nohitdelay reloadconfig &7(~~~)"
