name: NoHitDelay
version: '1.0'
main: newamazingpvp.nohitdelay.NoHitDelay
softdepend:
  - MythicMobs
commands:
  nohitdelay:
    description: Manage hit delay settings.
    usage: /nohitdelay <setdelay|getdelay|setmode|getmode|reloadconfig> [value]
    permission: nohitdelay.manage
    default: op
